#Please note the app will have all admin right inside the cluster
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-app-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-app-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: my-app-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-creator
  labels:
    operator: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      operator: demo
  template:
    metadata:
      labels:
        operator: demo
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      containers:
      - name: restapi
        image: <image name>